<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_O campo Senha  obrigatrio</name>
   <tag></tag>
   <elementGuidId>dea02039-69c9-48f3-900d-b169e6c08621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Password-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Password-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;O campo Senha é obrigatório.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7cb6fac9-ba54-4fbc-977b-ab6de935c712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Password-error</value>
      <webElementGuid>9e48c6be-418f-4078-8680-5f0a705ec91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>O campo Senha é obrigatório.</value>
      <webElementGuid>b1240806-f3f3-480f-88af-bb4706904f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Password-error&quot;)</value>
      <webElementGuid>42d915bd-72e9-4487-8e63-36525835ba3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Password-error']</value>
      <webElementGuid>9f012afd-2d37-4056-a851-bee62c10a0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div[2]/span/span</value>
      <webElementGuid>89685ffa-617e-4021-99cc-ab00e81717e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senha'])[1]/following::span[2]</value>
      <webElementGuid>ad423e1d-5caf-4eb0-bb13-cd20f7093f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O campo E-mail é obrigatório.'])[1]/following::span[2]</value>
      <webElementGuid>1de2ede5-12f4-4db6-aeee-d49c0a769e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[2]/preceding::span[1]</value>
      <webElementGuid>623a83a9-e07e-4c11-91aa-b00aead5357f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset de senha'])[1]/preceding::span[3]</value>
      <webElementGuid>05d13b9b-8d67-4b05-aeeb-db5a4a8da84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='O campo Senha é obrigatório.']/parent::*</value>
      <webElementGuid>458b6c43-cc9e-4b2e-a568-91450c7d03e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span</value>
      <webElementGuid>ef371104-1752-4a8c-b540-549397141a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Password-error' and (text() = 'O campo Senha é obrigatório.' or . = 'O campo Senha é obrigatório.')]</value>
      <webElementGuid>73cb3f1b-3375-469d-80ea-e4a840bbe679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
