<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b50315b2-c76b-40a8-b5b6-13d28578b8b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > img[alt=&quot;Logomarca Fórmulas COGE&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view']/div/div/div[2]/div/div/div[2]/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Logomarca Fórmulas COGE&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>be813207-991c-4afd-9742-2a4a25f24399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.funcoge.org.br/images/forms/logo.png</value>
      <webElementGuid>6b0ade10-4ded-4d07-a2bd-d38a7064775f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logomarca Fórmulas COGE</value>
      <webElementGuid>9fd1181f-7377-4016-b134-7dad36f8dbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logomarca Fórmulas COGE</value>
      <webElementGuid>b7ba73bb-0081-446d-aa51-b5c664338bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view&quot;)/div[@class=&quot;padding&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 push-md-2 col-md-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;box p-a&quot;]/div[@class=&quot;icon&quot;]/span[1]/img[1]</value>
      <webElementGuid>8e392483-1b1b-4405-b1a3-f0178d61a995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div/div[2]/div/div/div[2]/div/div/span/img</value>
      <webElementGuid>2acb74da-7063-45e2-81bb-272c7814486e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Logomarca Fórmulas COGE'])[2]</value>
      <webElementGuid>98e22749-786d-46c3-a4e5-c9a3bcb4a268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>0e762285-1943-401a-86e8-d088badf6101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.funcoge.org.br/images/forms/logo.png' and @alt = 'Logomarca Fórmulas COGE' and @title = 'Logomarca Fórmulas COGE']</value>
      <webElementGuid>56b3be83-b1f6-463b-aeee-617404afb13c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
