<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i</name>
   <tag></tag>
   <elementGuidId>616868be-c6ce-4ed3-ae9b-21f09cf6f6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[2]/div/div/div[2]/div/div/div[3]/form/div/div[2]/div[3]/div[1]/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2ece37ab-c94c-4feb-b779-017cb0dedd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>808a7de6-0390-4601-b6bd-535c43320885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loadingForm&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;form-group col-xs-6&quot;]/div[@class=&quot;col-sm-2&quot;]/label[@class=&quot;ui-switch ui-switch-md blue m-t-xs&quot;]/i[1]</value>
      <webElementGuid>a07809cf-4c97-4585-9f28-29ba1779e96e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div[3]/div/div/label/i</value>
      <webElementGuid>dcc7d654-a059-408b-aeac-f6aac02303fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>d80f7d6b-14e0-42f4-adb3-52716949cbd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
