<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero do Processo_Report.ProcessNumber</name>
   <tag></tag>
   <elementGuidId>ae8ce85e-c832-4e18-9b31-8fe0de4510be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Report_ProcessNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Report_ProcessNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Número do Processo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c108e5b6-0194-4616-a116-2a4fe4c92bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>2c3c5399-ec26-4736-bd2e-b9c17e1bb1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Report_ProcessNumber</value>
      <webElementGuid>5e92e48b-c846-4803-8c31-586800f53df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Report.ProcessNumber</value>
      <webElementGuid>75e64e12-4673-403a-90fa-78bed3bada8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Número do Processo</value>
      <webElementGuid>a068b2ca-2626-418e-a4b7-ec56d501deb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2c57d4a-0bc9-47f2-bd2a-3cbb963bba84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Report_ProcessNumber&quot;)</value>
      <webElementGuid>ec245b9b-14ea-4bf5-b041-d8ea63115ab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Report_ProcessNumber']</value>
      <webElementGuid>ccbb8c27-011b-4d8a-8712-ae4d5ea474c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>4debd63a-4db4-4564-a421-14971fe2817a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>14d5c076-8701-45e2-884a-cbdb2c2320f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Report_ProcessNumber' and @name = 'Report.ProcessNumber' and @placeholder = 'Número do Processo' and @type = 'text']</value>
      <webElementGuid>75272c79-f0c2-4fed-a2ff-ed2615a2c7c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
