<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Formato 0.00_value</name>
   <tag></tag>
   <elementGuidId>d84d9be9-1eaa-48dc-98ba-0e1f9923569f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#value</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24406b69-de65-45f7-a7cf-513c75849270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b40a21d1-401e-43c4-8367-e9fd30758136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>bc77b7cd-81da-460c-b86d-356ce9e855c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>c4554276-06cc-4468-a450-7486648bfb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e792b125-90a4-4f79-8364-98abcc1e1804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;value&quot;)</value>
      <webElementGuid>d50086cd-d1cd-423b-a5ac-c2e4ee805a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='value']</value>
      <webElementGuid>8f579810-ff1a-4770-bb48-48430209cf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div/div[4]/div/div[2]/form/div/div/input</value>
      <webElementGuid>c02c8a0d-491f-471f-a869-55e1ec13960c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>cf97735a-fc97-41b0-aa84-1a2c5ba8b7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'value' and @name = 'value' and @type = 'text']</value>
      <webElementGuid>ef85e2a3-d5f7-480c-a639-c78d40fbc837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
