<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Selecione-_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>560b6896-d1aa-4cb1-ae64-3e3e975d79c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Period_EndMonth-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-Period_EndMonth-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;-Selecione-&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27012b88-cfb7-45be-8e18-e74255da62a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>41b59066-e49e-4cf7-8879-b2fa8e856625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Period_EndMonth-container</value>
      <webElementGuid>6994d7de-16ea-45ca-85bc-09744be13516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>761f374c-4fa3-47b2-9aa0-016d4cbb9414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e08d08f5-3c53-4a5b-bb9e-e2e5183c73bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>4633eb9f-0b26-40ad-9639-7f5fcc67d549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>94e7465b-cf3e-45b0-bb03-03c66c6f1886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Period_EndMonth-container&quot;)</value>
      <webElementGuid>fc930e43-0829-41cc-8b32-d3404470e7dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-Period_EndMonth-container']</value>
      <webElementGuid>ae4b7461-3bdd-499e-88fa-3766f234acb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div[6]/div[2]/span/span/span/span</value>
      <webElementGuid>323a91c6-5826-4512-8d55-c0e47080fea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mês Termo'])[1]/following::span[4]</value>
      <webElementGuid>54f107d4-6e0c-423e-81b5-e21a07b1b018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ano Termo'])[1]/following::span[11]</value>
      <webElementGuid>29f6e7c6-f375-4d36-8c34-3e63f347389e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exibir'])[1]/preceding::span[4]</value>
      <webElementGuid>86e1b394-52e4-4372-9f63-5596d590c055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Última atualização dos indicadores:'])[1]/preceding::span[5]</value>
      <webElementGuid>c59bd40a-a9d0-467c-a001-a08f7f204f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/span/span/span/span</value>
      <webElementGuid>3de80123-abce-4f59-b017-9875f9e1aa50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Period_EndMonth-container' and @title = '-Selecione-' and (text() = '-Selecione-' or . = '-Selecione-')]</value>
      <webElementGuid>2ef9f5ba-74d8-4b21-ab40-50d529cf685c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
