<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ENTRAR</name>
   <tag></tag>
   <elementGuidId>3676e391-855a-4bcf-9942-b268b35ad26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='loginspannk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginspannk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ENTRAR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f79de2f-178d-49a5-ac86-718944f4effc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>79770692-7672-47e4-95ce-a62f499ee261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/conta/entrar</value>
      <webElementGuid>20ab4a42-ec5f-416e-99d2-20f2299ef2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginspannk</value>
      <webElementGuid>5bf5da4a-a169-4431-9872-57e4e3b71962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ENTRAR</value>
      <webElementGuid>d499babf-0ea1-4962-b4fc-a3a097d97ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginspannk&quot;)</value>
      <webElementGuid>df6baacb-a501-46a8-a921-e9bfb4a49dc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='loginspannk']</value>
      <webElementGuid>a19b5750-3e54-417e-bc23-803f8e521d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/ul/li[2]/a</value>
      <webElementGuid>d4533014-6423-4266-a07d-75366f00c90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ENTRAR')]</value>
      <webElementGuid>922aa501-2bf7-4d44-bd52-f9831e3c3995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[1]/following::a[1]</value>
      <webElementGuid>05d601eb-5f15-4f57-8ee4-6780abeb2906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/preceding::a[1]</value>
      <webElementGuid>c5770f3e-9a0d-4759-a5c3-9e602033cec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONCEITOS'])[1]/preceding::a[2]</value>
      <webElementGuid>95f4b6af-de35-49e3-9621-a269fd36aa57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ENTRAR']/parent::*</value>
      <webElementGuid>35a6de4f-52e7-4cae-9f96-8740bff9fd3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/conta/entrar')]</value>
      <webElementGuid>4b666b84-f4c5-40ea-8130-4ff854b1027b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>c376b4c3-45ff-4275-a2fa-582d8325bf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/conta/entrar' and @id = 'loginspannk' and (text() = ' ENTRAR' or . = ' ENTRAR')]</value>
      <webElementGuid>2a844db9-41f1-4ce3-9a05-88fde35bacce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
