<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FCM0001 - Acessrios de Cabo de Cobre (_2d1641</name>
   <tag></tag>
   <elementGuidId>bdcca9ab-f030-43a7-99d0-9ac09d9d6621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-FormulaId-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-FormulaId-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>62fac193-5f7d-4da2-8c52-818dc236ff54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>abdf875c-d843-4d05-86d7-e7f68b1192cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-FormulaId-container</value>
      <webElementGuid>27e8d32a-acc2-4a30-b7db-6c38166b3008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>56027202-e854-4124-955f-cb7760699f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e91ca16d-de4a-4ce0-819c-fb8635549fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria)</value>
      <webElementGuid>21ec4bf4-0f00-4276-9f3f-1f588a8489e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria)</value>
      <webElementGuid>6a94aa87-fb6e-4cc5-8db9-a8b32b4c5add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-FormulaId-container&quot;)</value>
      <webElementGuid>963c4c34-d1c6-405f-8881-86aab8fbe99d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-FormulaId-container']</value>
      <webElementGuid>0cfed8c4-53da-4ba7-87af-068a9f9d1cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>41a84e42-a4f7-4a2f-8a30-5be9f1784ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fórmula COGE'])[1]/following::span[4]</value>
      <webElementGuid>0dd69716-a13e-4ab2-accf-efecf6f95e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulário de Registro'])[1]/following::span[4]</value>
      <webElementGuid>f627919b-ebe1-4db4-88bf-e1a4097796b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salvar'])[1]/preceding::span[4]</value>
      <webElementGuid>299ef3ac-2034-4481-b1c9-6624fd9db34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Última atualização dos indicadores:'])[1]/preceding::span[5]</value>
      <webElementGuid>dfc222f2-9aee-4fbf-b9fa-557b88a8f170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>91d68f8b-94e7-4771-b04e-d62172da0a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-FormulaId-container' and @title = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria)' and (text() = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria)' or . = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria)')]</value>
      <webElementGuid>86479813-9867-4c09-83ff-b710fe549e15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
