<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Selecione-</name>
   <tag></tag>
   <elementGuidId>d84b8693-0a0b-42ad-8a37-d399ef891f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-Id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-Id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-Id-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>07bb0ddf-5767-49d8-91d3-0624130d2ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f5f61f11-19e9-4f26-8c36-735801a889a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Id-container</value>
      <webElementGuid>55fe985a-47d1-43eb-844f-6c254bb54d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>12720b92-91cf-40f2-a21b-47249baee70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc42fbf7-4bc9-4b87-8259-3dd3d1b7a605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>08b61ba1-7188-48a9-a29f-24ba62a01f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>279fafd7-7a4a-4475-bfc7-68660b2ae92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Id-container&quot;)</value>
      <webElementGuid>b838e9f7-3cc3-49c5-94e6-1c0d8d60660e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-Id-container']</value>
      <webElementGuid>743b6710-0f55-4d55-916f-069c8a3b8040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>e490263d-f9c0-4dfc-a4ab-1c50d1a44c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fórmula'])[1]/following::span[4]</value>
      <webElementGuid>9c9442fa-18d8-4dab-bffc-d13fcec8d7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulário de Pesquisa'])[1]/following::span[4]</value>
      <webElementGuid>52d08976-47ed-4443-8097-ac9b57ca249d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modo Relatório'])[1]/preceding::span[4]</value>
      <webElementGuid>bb78d3b9-46fe-471d-b777-b0bdbe0b8332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número do Processo'])[1]/preceding::span[4]</value>
      <webElementGuid>c4f5af3f-4454-4cc6-aec1-2303ade9ae85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>5a77fbb8-befe-4afe-b3fc-bbb962154ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Id-container' and @title = '-Selecione-' and (text() = '-Selecione-' or . = '-Selecione-')]</value>
      <webElementGuid>de644e2a-d300-495b-ae86-519ff109c820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
