<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FCM0001 - Acessrios de Cabo de Cobre (_2d1641</name>
   <tag></tag>
   <elementGuidId>e3321463-16a9-427f-b0b4-7eeba238e384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[2]/div/div/div[2]/div/div/div[3]/form/div/div[2]/div[1]/div/span[1]/span[1]/span/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-Id-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select2-Id-container' and @title = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria) ' and (text() = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria) ' or . = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria) ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7511f5fc-5cf3-4a53-9950-e5080bc6ede7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7d2fef1c-01b7-4c7b-bd30-8ff86049c168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Id-container</value>
      <webElementGuid>b7f3c77c-e036-4683-af3c-072da853dbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3ecbdc36-2ab7-41e5-a9a8-4fd3911833a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed070a0b-a978-40c0-a03f-a93caf74d91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria) </value>
      <webElementGuid>5bdec0b3-8be8-4579-b5fd-e94d3702905b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria) </value>
      <webElementGuid>07f9b422-f566-43e7-b299-f4eb7648f4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Id-container&quot;)</value>
      <webElementGuid>786f2c8c-caf9-4f3c-8b6e-fa34149479be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-Id-container']</value>
      <webElementGuid>76948160-11b8-4a77-a5c4-2f34bc1ddde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>3bce3972-9aaf-4ebf-960e-eb45e4681ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fórmula'])[1]/following::span[4]</value>
      <webElementGuid>d20dcc7c-560b-49d3-b5da-a0e0264bbe08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulário de Pesquisa'])[1]/following::span[4]</value>
      <webElementGuid>2382ee51-73c6-45be-a687-6181d0f901c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modo Relatório'])[1]/preceding::span[4]</value>
      <webElementGuid>3500ac0e-4cf1-4688-883b-e852d18e3a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número do Processo'])[1]/preceding::span[4]</value>
      <webElementGuid>161c05ba-1774-4494-975d-4ddac7703a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>3ae801b8-18cd-4d92-ae41-97ba80c73cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Id-container' and @title = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria) ' and (text() = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria) ' or . = 'FCM0001 - Acessórios de Cabo de Cobre (Exceto os Materiais com Fórmula Própria) ')]</value>
      <webElementGuid>54fd6d43-e2eb-43d0-8401-23e3f2cba7d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
