<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Deletar</name>
   <tag></tag>
   <elementGuidId>32623042-6a3d-41f8-ab6e-e8f732690e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view']/div/div/div[4]/div/div[2]/div/table/tbody/tr/td/span/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Deletar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80d8116a-40f8-4c88-bc99-7b9c5d4526fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger</value>
      <webElementGuid>4a579049-71a3-43d6-95f8-16f993de7580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>confirm</value>
      <webElementGuid>62743f40-d6ea-4555-aed1-cc52e2cf5899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9124e8a8-55f8-4494-8805-1e3e9afdf123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/relatorio-grafico/deletar-valor-referencia/formula/</value>
      <webElementGuid>5e5a6b8b-a2d7-41de-83e2-e147b01ce0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deletar</value>
      <webElementGuid>50b0cca3-0dc0-4428-be4e-6f54a0917c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view&quot;)/div[@class=&quot;padding&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8 col-md-2&quot;]/div[@class=&quot;box light lt&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;clear p-a-xs&quot;]/table[@class=&quot;table table-condensed table-striped&quot;]/tbody[1]/tr[1]/td[1]/span[@class=&quot;clearfix js-sweetalert&quot;]/button[@class=&quot;btn btn-sm btn-danger&quot;]</value>
      <webElementGuid>bab6c4a0-8245-41bc-a654-479d6e710442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div/div[4]/div/div[2]/div/table/tbody/tr/td/span/button</value>
      <webElementGuid>7e3c736f-19fc-4707-a4f5-655857699dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='($)10.00'])[1]/following::button[1]</value>
      <webElementGuid>1ceb87d7-365e-4c58-bd5c-44112f93a49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valores'])[1]/following::button[1]</value>
      <webElementGuid>49d2ffd0-04d0-4962-89d7-5b8bbf2fd28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[2]/preceding::button[1]</value>
      <webElementGuid>a0855875-6acf-4d4e-9216-cf3c031ca746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deletar']/parent::*</value>
      <webElementGuid>e76c7b2b-4941-4c0b-95d2-538834154071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>f17ef50f-d1ca-4243-b778-443866c5f5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Deletar' or . = 'Deletar')]</value>
      <webElementGuid>f6f7ff48-1714-418f-aa9c-78bc6eea34d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
