<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero do Processo_Report.ProcessNumber</name>
   <tag></tag>
   <elementGuidId>f25ad6e1-a740-4c9e-a567-d7a1fd7f2d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Report_ProcessNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Report_ProcessNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Número do Processo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab9999cb-aa35-4937-96fe-49a5bc1dd79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>70c47263-357e-449c-ab87-a9ba9155581d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Report_ProcessNumber</value>
      <webElementGuid>44df7efa-e539-4a2a-8dbc-fe2a1041af96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Report.ProcessNumber</value>
      <webElementGuid>ee26bd82-19fe-4e8f-9960-43d50caf5da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Número do Processo</value>
      <webElementGuid>50b5f48d-57fa-40ba-ae3f-2bfc9558fcb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc7dbeb0-67d4-4249-964c-49f7d106cfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Report_ProcessNumber&quot;)</value>
      <webElementGuid>020108c9-49a1-4218-a408-de47fb0f202b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Report_ProcessNumber']</value>
      <webElementGuid>5488fe3e-d312-4b76-8ac0-c6ba4171aa22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>178bf3a5-85f7-4cfb-b8e9-1c2cd03ea136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cfedf002-d920-4988-9362-8434bc43ad4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Report_ProcessNumber' and @name = 'Report.ProcessNumber' and @placeholder = 'Número do Processo' and @type = 'text']</value>
      <webElementGuid>9011bad6-68db-4600-a17a-9730fea68b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
