<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FCM0010 - Bandeja e Suporte para Cabo _0dde80</name>
   <tag></tag>
   <elementGuidId>c940ef34-2e38-4c6e-85f9-8e322369515f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-Id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-Id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;FCM0010 - Bandeja e Suporte para Cabo Com Projetos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4b0a34f-542f-44e2-adc7-514fe527b2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>43a82da8-8d58-4cba-828f-74488848c238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Id-container</value>
      <webElementGuid>d7c2bee8-022a-42e2-8a41-906b5d703095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>179e5272-eb5c-4bc0-8786-d9c947e919e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e8a8ee8-ef28-4c74-98c7-6bcda258b15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>FCM0010 - Bandeja e Suporte para Cabo Com Projetos </value>
      <webElementGuid>735ddf89-f068-4042-acbc-c715e29832c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FCM0010 - Bandeja e Suporte para Cabo Com Projetos </value>
      <webElementGuid>cb045852-ccd5-4a0c-83e1-c34c0afa5b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Id-container&quot;)</value>
      <webElementGuid>a4de1276-6c6f-4bf6-bcad-eefbf50fd349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-Id-container']</value>
      <webElementGuid>5facb257-7298-4fe7-b7cd-a418ca5f663a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>5407d1de-c2fe-45e5-a9a2-72815b686321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fórmula'])[1]/following::span[4]</value>
      <webElementGuid>25d16a97-7bb2-430e-a47a-878beee02d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulário de Pesquisa'])[1]/following::span[4]</value>
      <webElementGuid>dc0c7b00-c612-4bd0-a4df-eafa8e815c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modo Relatório'])[1]/preceding::span[4]</value>
      <webElementGuid>e4f60097-917e-4348-89e8-d170219474a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número do Processo'])[1]/preceding::span[4]</value>
      <webElementGuid>70b73000-bd7b-4e31-ab33-7ccfb3175fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>9d85ef41-d714-4976-983c-bfee9ed855a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Id-container' and @title = 'FCM0010 - Bandeja e Suporte para Cabo Com Projetos ' and (text() = 'FCM0010 - Bandeja e Suporte para Cabo Com Projetos ' or . = 'FCM0010 - Bandeja e Suporte para Cabo Com Projetos ')]</value>
      <webElementGuid>7cceb731-473a-4a63-9743-290606007d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
