<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Selecione-_1</name>
   <tag></tag>
   <elementGuidId>55013450-c117-447d-b509-bc1a3bf60a77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-Period_StartYear-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-Period_StartYear-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-Period_StartYear-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e24f01dd-f923-47c9-9802-b85002c4c881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b6511c36-0787-4ff4-be86-b78eec0c3998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Period_StartYear-container</value>
      <webElementGuid>69a88e14-279e-4bbf-956d-5506b1d4e1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>76b1845e-ec06-413e-9875-4c82ddd4577e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b71c16b-9f46-44c9-b0db-0d41cedc8648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>f4a3560f-d706-4102-a583-7fa07905a01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>f0b78139-9c98-43dd-bd53-5d6647dd31cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Period_StartYear-container&quot;)</value>
      <webElementGuid>216de455-7853-470d-8f1f-aaa38e1cb8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-Period_StartYear-container']</value>
      <webElementGuid>5cf28ae7-5b53-446d-9a71-75953b83a835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div[5]/div/span/span/span/span</value>
      <webElementGuid>30f04e92-73ad-4b53-aa0c-91f7fdee93c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ano Inicial'])[1]/following::span[4]</value>
      <webElementGuid>e1292f85-5d9f-4a22-9986-f97647ad33ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número do Processo'])[1]/following::span[5]</value>
      <webElementGuid>7699a65a-eadd-496e-a55c-8129c4de0220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mês Inicial'])[1]/preceding::span[4]</value>
      <webElementGuid>415004fb-6799-40a1-b757-0a3b772bd620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Selecione-'])[5]/preceding::span[4]</value>
      <webElementGuid>3c80dbfd-d3f9-42e6-92a6-a8f591487491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/span/span/span</value>
      <webElementGuid>625e7044-9f15-4c5c-8af6-a2ab2c73b562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Period_StartYear-container' and @title = '-Selecione-' and (text() = '-Selecione-' or . = '-Selecione-')]</value>
      <webElementGuid>65f59427-67ce-45fb-8d3a-705ef30ac0f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
