<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Selecione-_1_2</name>
   <tag></tag>
   <elementGuidId>a207b186-8905-42dd-a274-7207c38b93de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-Period_StartMonth-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-Period_StartMonth-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-Period_StartMonth-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dba37977-8eca-4a80-9f98-7f086cc3843c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>003a1aa0-0ffb-4052-85d1-7661ad84a098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Period_StartMonth-container</value>
      <webElementGuid>ff5a10a4-15cb-4909-916d-35fc85763cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2169e06f-0f8e-40cf-9209-3689e89cbb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80de2051-ba7f-4f05-8cfe-3f521483967c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>1c0cae04-09b8-422b-8ce4-fb5bb8062d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>9a4b870b-d7a7-48d1-9c8a-c46f00c009ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Period_StartMonth-container&quot;)</value>
      <webElementGuid>294ba77e-44e6-4536-b9a3-da06de3cf5dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-Period_StartMonth-container']</value>
      <webElementGuid>51c06f5c-e898-4330-912a-255348ad6c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div[5]/div[2]/span/span/span/span</value>
      <webElementGuid>c170d59a-cce2-407d-99db-b9a4012f497e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mês Inicial'])[1]/following::span[4]</value>
      <webElementGuid>ed13d6dc-d808-4e5b-b0fa-9916010647b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ano Inicial'])[1]/following::span[11]</value>
      <webElementGuid>c40f4ca7-ae4f-4df4-9da1-574d0d7a059e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ano Termo'])[1]/preceding::span[4]</value>
      <webElementGuid>86a1dc3c-b384-41ed-ab08-279743e4031a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Selecione-'])[6]/preceding::span[4]</value>
      <webElementGuid>642d7c47-9b89-44d3-a436-ca7b326d6c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>1bfe5f97-ae16-405c-aa94-abf2b3b1cd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Period_StartMonth-container' and @title = '-Selecione-' and (text() = '-Selecione-' or . = '-Selecione-')]</value>
      <webElementGuid>3ff28a74-7584-4641-9fd5-ff005e1882c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
