<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Selecione-_1_2_3</name>
   <tag></tag>
   <elementGuidId>1a1e800b-d8e2-4ce1-8af3-c01c6c78a7e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-Period_EndYear-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-Period_EndYear-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-Period_EndYear-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2eabc1d-b0a7-4dac-9925-751dba0b37ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>dca984b2-3562-4a1d-99d1-411c102eafe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Period_EndYear-container</value>
      <webElementGuid>a84f9a25-1cbf-482d-a0ec-76f50ee28f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0c68e0ad-ed88-4f2b-9ea6-892f8a59ee88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce34f649-70dd-414b-859e-16ee72293c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>3f05a377-95e4-4434-9c69-397ec6800ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Selecione-</value>
      <webElementGuid>e854fcb6-b0a2-48d3-bb9f-73cc2c3c1274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Period_EndYear-container&quot;)</value>
      <webElementGuid>37abc55f-4b9f-4c97-bf84-fa25f5274baf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-Period_EndYear-container']</value>
      <webElementGuid>54cba43f-adc5-4abe-b7e6-b8aa10595f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loadingForm']/div/div[2]/div[6]/div/span/span/span/span</value>
      <webElementGuid>5ab70bca-d240-470b-b412-22506e757fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ano Termo'])[1]/following::span[4]</value>
      <webElementGuid>2665c60a-9239-441a-889d-223ba6a7ad7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Janeiro'])[2]/following::span[7]</value>
      <webElementGuid>9a8f34f9-5de4-4586-9c4c-20e330cd61e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mês Termo'])[1]/preceding::span[4]</value>
      <webElementGuid>de632f70-2c18-4785-adf6-3bfd3e5f97f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Selecione-'])[7]/preceding::span[4]</value>
      <webElementGuid>be1afe73-9ea6-4c3e-8b15-5ca953cecc7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span/span/span/span</value>
      <webElementGuid>df44b889-d937-4fd9-9030-dfafc8cf95b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Period_EndYear-container' and @title = '-Selecione-' and (text() = '-Selecione-' or . = '-Selecione-')]</value>
      <webElementGuid>d8c36bde-08db-4eee-88a4-ae8b42e12e80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
