<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Deletar</name>
   <tag></tag>
   <elementGuidId>f9f05151-0d8f-4095-8fe3-1d1354c7ef0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='data-table']/tbody/tr/td[3]/span/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;FCM0003 - Acessórios Não Ferrosos / Latão em Ligas de Cobre (Bronze / Latão) NÃO Deletar&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa8ad5f3-0654-49b7-bd6d-f85053cd10da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger</value>
      <webElementGuid>c44bbd8b-2b90-437f-9aea-f7ffc0423d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>confirm</value>
      <webElementGuid>b19a0c35-c764-482d-9816-5c05e892d2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>79c69026-909c-4a48-baba-ef5911d6d6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/favoritos/deletar/</value>
      <webElementGuid>b2e4f088-fabf-47a5-a150-df8da51dbf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deletar</value>
      <webElementGuid>d14401b6-fedd-4772-b17b-c4bd7af1e5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-table&quot;)/tbody[1]/tr[@class=&quot;ng-scope odd&quot;]/td[@class=&quot;v-middle&quot;]/span[@class=&quot;clearfix js-sweetalert&quot;]/button[@class=&quot;btn btn-sm btn-danger&quot;]</value>
      <webElementGuid>4e34d89e-c623-411a-93da-f94bd002428f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='data-table']/tbody/tr/td[3]/span/button</value>
      <webElementGuid>e1daba51-05cd-49e5-a585-44969f3916c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NÃO'])[1]/following::button[1]</value>
      <webElementGuid>b7689d4e-3b28-4830-b5c0-b824c7eac466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FCM0003 - Acessórios Não Ferrosos / Latão em Ligas de Cobre (Bronze / Latão)'])[1]/following::button[1]</value>
      <webElementGuid>72336073-c2f4-48a6-80de-7494cfe2d4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FCM0004 - Alça Pré-Formada de Aço Revestida com Alumínio'])[1]/preceding::button[1]</value>
      <webElementGuid>ad51be4e-2ae5-439d-ac7d-0edcb7206115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NÃO'])[2]/preceding::button[1]</value>
      <webElementGuid>ea102b16-24a1-4da9-bc05-81d9e4e81d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deletar']/parent::*</value>
      <webElementGuid>58dbb341-8bf2-40c3-9058-2166e5eb7184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>e84f2791-4cc7-4a3b-a7e3-b273b6551cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Deletar' or . = 'Deletar')]</value>
      <webElementGuid>da089bf1-5e0c-448d-9d9e-dba34bc59c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
