<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Total de 4 favoritos_fas fa-bars</name>
   <tag></tag>
   <elementGuidId>456ea456-a3c6-4b2d-a9d9-cf8057237ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view']/div/div/div[2]/div/div/div[2]/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fas.fa-bars</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Registrar Favorito Meu Perfil&quot;i >> a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f32f3e1-9886-4ab7-9255-e7ee7f13291c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-bars</value>
      <webElementGuid>c35b56f0-e7cd-4701-bd00-078a1fb08d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menu de Contexto</value>
      <webElementGuid>4e37f83d-f1f7-4aa5-a762-23c0a790ea36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view&quot;)/div[@class=&quot;padding&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 push-md-2 col-md-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;box-tool&quot;]/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item inline dropdown&quot;]/a[@class=&quot;nav-link&quot;]/span[@class=&quot;fas fa-bars&quot;]</value>
      <webElementGuid>e9b44eb7-61d9-4261-b3c7-821cfe1563dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div/div[2]/div/div/div[2]/ul/li[2]/a/span</value>
      <webElementGuid>94a05d8a-ccdb-406f-820b-cab96e17d7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a/span</value>
      <webElementGuid>57e1a433-bb0c-4091-8fbf-b324a949a40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Menu de Contexto']</value>
      <webElementGuid>4a63cc01-613a-4287-870a-1bd1c7e54e95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
