<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Grfico de Tendncia_canvas</name>
   <tag></tag>
   <elementGuidId>8a5088cf-d980-4755-b3f1-0be777318a7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='canvas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>75a3b445-b7c6-4555-8c66-bb1b8dbaf632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>2efd7b62-7381-4f4a-9a9f-c69c4aaa3594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>1d721f19-b4a5-4fb0-a9eb-76d56f0a2932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>517</value>
      <webElementGuid>bb3bf569-c0ce-42a2-bc21-f46a994e8074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;canvas&quot;)</value>
      <webElementGuid>a06433d3-3dd6-4242-b5d8-e8e8e9efc731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='canvas']</value>
      <webElementGuid>71f3b22d-b467-4624-b7fb-f1f6ad98e6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view']/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div/canvas</value>
      <webElementGuid>f22cf371-5361-4701-ade5-f0891a2e5776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>d94d955c-620f-466f-9697-627af4356890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'canvas']</value>
      <webElementGuid>fb898306-3cc8-4f3c-8471-0beb70c3fefc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
